version: '3'
services:
  nginx-rtmp:
    build: .
    container_name: nginx-rtmp
    environment:
      - RTMP_PORT=1935
      - HTTP_PORT=8080
      - HLS_FRAGMENT_LENGTH=3
      - HLS_PLAYLIST_LENGTH=20
    ports:
      - "1935:1935"
      - "8080:8080"
